name: colt_ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Styling
  cupertino_icons: ^1.0.8          # iOS-style icons
  flutter_svg: ^2.2.0              # SVG rendering and widget library
  flutter_screenutil: ^5.9.3       # Screen and font size adaptation

  # Network and Connectivity
  data_connection_checker_tv: ^0.3.5-nullsafety  # Internet connectivity checker
  dio: ^5.9.0                      # HTTP client for API calls
  pretty_dio_logger: ^1.4.0        # Network calls logging
  retrofit: ^4.6.0                 # Type-safe HTTP client
  retrofit_generator: ^10.0.0      # Code generation for retrofit

  # State Management
  flutter_bloc: ^9.1.1             # BLoC pattern implementation
  get_it: ^8.0.3                   # Dependency injection

  # Storage
  shared_preferences: ^2.5.3       # Persistent storage

  # Code Generation and Serialization
  freezed: ^3.2.0                  # Code generation for data classes
  build_runner: ^2.3.3             # Code generation tool
  json_serializable: ^6.7.1        # JSON serialization
  json_annotation: ^4.9.0          # JSON annotations
  freezed_annotation: ^3.1.0       # Freezed annotations

  # Localization
  intl: ^0.20.2                    # Internationalization support
  easy_localization: ^3.0.7+1      # Simplified localization

  # Firebase
  firebase_core: ^4.0.0            # Firebase core functionality

  # Splash Screen
  flutter_native_splash: ^2.4.6    # Native splash screen
  flutter_gen: ^5.12.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0            # Recommended Flutter lints

# flutter:
#   uses-material-design: true
#   assets:
