name: colt_ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Styling
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  flutter_screenutil: ^5.9.3

  # Network and Connectivity
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.6.0
  retrofit_generator: ^10.0.0

  # State Management
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3

  # Storage
  shared_preferences: ^2.5.3

  # Code Generation and Serialization
  freezed: ^3.2.0
  build_runner: ^2.6.0
  json_serializable: ^6.11.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

  # Localization
  intl: ^0.20.2
  easy_localization: ^3.0.7+1
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.3.3
  intl_utils: ^2.8.12

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.1.1
  flutter_facebook_auth: ^7.1.2

  # Splash Screen
  flutter_native_splash: ^2.4.6
  persistent_bottom_nav_bar: ^6.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/icon/
    - lib/l10n/intl_ar.arb
    - lib/l10n/intl_en.arb

  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: asset/fonts/NotoKufiArabic-Regular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: asset/fonts/Inter.ttc
          weight: 400

flutter_intl:
  enabled: true
  class_name: T
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/core/generated/l10n
